version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - export BUCKET=codebuild-us-east-1-510690132021
      - export REACT_BUILD_S3_BUCKET=gig-viz-assets
      - export REACT_BUILD_S3_FOLDER=$(date -Iminutes)
      - export REACT_BUILD_S3_URL=s3://$REACT_BUILD_S3_BUCKET/$REACT_BUILD_S3_FOLDER
      - aws s3 cp ./build $REACT_BUILD_S3_URL --recursive
      - ./create-template-config
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outtemplate.yml
artifacts:
  files:
    - template-config.json
    - outtemplate.yml
    - template.yml